pipeline {
    agent {
        docker { image 'openjdk:17' }
    }
    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/your-repository-url.git'
            }
        }
        stage('Compile') {
            steps {
                sh 'javac HelloWorld.java'
            }
        }
        stage('Run') {
            steps {
                sh 'java HelloWorld'
            }
        }
    }
}

